# =============================================================================
# intelligence/deduplicator.py — Cross-Portal Duplicate Detection
#
# Two-level deduplication strategy:
#
#   Level 1 — Hash dedup (exact cross-portal match)
#     • Compares content_hash (MD5 of sorted, stop-word-stripped title tokens)
#     • Generated by normalizer.NormalizedTender._content_hash()
#     • Catches: same tender posted on UNDP + UNGM with minor formatting diffs
#     • Cost: O(1) MySQL lookup
#
#   Level 2 — Semantic dedup (near-duplicate detection)
#     • Sentence-transformer embedding → ChromaDB cosine similarity (≥0.95)
#     • Generated by intelligence_layer (sentence-transformers all-MiniLM-L6-v2)
#     • Catches: same tender reworded or reposted with slightly different title
#     • Cost: O(log n) ChromaDB query (can be skipped if embedding unavailable)
#
# Usage:
#   from intelligence.deduplicator import check_duplicate, DedupResult
#
#   result = check_duplicate(
#       content_hash="abc123",
#       tender_id="wb_001",
#       title="Baseline Survey for WASH",
#       embedding=np.array(...),    # optional — skips semantic check if None
#   )
#   if result.is_new:
#       # proceed with save + notification
# =============================================================================

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger("tenderradar.deduplicator")


# =============================================================================
# Result dataclass
# =============================================================================

@dataclass
class DedupResult:
    """
    Outcome of a duplicate check.

    Attributes:
        is_new        : True  → tender is genuinely new, proceed normally.
                        False → duplicate found, suppress alert.
        canonical_id  : tender_id of the first-seen original (if is_new=False).
        dedup_type    : "hash" | "semantic" | "none" (for new tenders).
        similarity    : Cosine similarity (0.0–1.0) if semantic dedup triggered.
        source_portal : Portal where the duplicate was originally seen.
    """
    is_new:        bool
    canonical_id:  Optional[str]  = None
    dedup_type:    str             = "none"   # "none" | "hash" | "semantic"
    similarity:    float           = 0.0
    source_portal: Optional[str]  = None

    @property
    def is_duplicate(self) -> bool:
        return not self.is_new


# =============================================================================
# Public API
# =============================================================================

def check_duplicate(
    content_hash:     str,
    tender_id:        str,
    title:            str             = "",
    embedding:        Optional[object] = None,
    semantic_threshold: float          = 0.95,
) -> DedupResult:
    """
    Check whether this tender is a cross-portal duplicate.

    Args:
        content_hash      : MD5 from NormalizedTender.content_hash.
        tender_id         : Unique ID for this tender (e.g. "wb_abc123").
        title             : Human-readable title (used only for logging).
        embedding         : numpy array from sentence-transformers (optional).
                            Pass None to skip Level 2 semantic check.
        semantic_threshold: Cosine similarity cutoff (default 0.95).

    Returns:
        DedupResult — check .is_new before saving / alerting.
    """
    # ── Level 1: hash dedup ───────────────────────────────────────────────────
    hash_result = _check_hash_duplicate(content_hash, tender_id)
    if hash_result is not None:
        logger.info(
            f"[dedup] Hash duplicate: '{title[:60]}' "
            f"→ canonical={hash_result.canonical_id}"
        )
        return hash_result

    # ── Level 2: semantic dedup (only if embedding provided) ─────────────────
    if embedding is not None:
        sem_result = _check_semantic_duplicate(
            embedding, tender_id, title, semantic_threshold
        )
        if sem_result is not None:
            logger.info(
                f"[dedup] Semantic duplicate: '{title[:60]}' "
                f"→ similarity={sem_result.similarity:.3f}"
            )
            return sem_result

    # ── New tender ────────────────────────────────────────────────────────────
    return DedupResult(is_new=True, dedup_type="none")


def register_tender(
    content_hash: str,
    tender_id:    str,
    source_portal: str = "",
) -> bool:
    """
    Register a tender's hash fingerprint after it has been accepted as new.

    Call this AFTER check_duplicate returns is_new=True, BEFORE saving to
    seen_tenders, to prevent a concurrent scraper run from inserting the same
    cross-portal tender twice.

    Returns True on success, False on any DB error (non-fatal).
    """
    return _store_hash_fingerprint(content_hash, tender_id, source_portal)


# =============================================================================
# Level 1 — Hash dedup helpers
# =============================================================================

def _check_hash_duplicate(
    content_hash: str,
    tender_id:    str,
) -> Optional[DedupResult]:
    """
    Query the tender_hashes table.
    Returns DedupResult(is_new=False) if a match found, else None.
    """
    if not content_hash:
        return None

    try:
        from database.db import get_connection
        conn = get_connection()
        cur  = conn.cursor(dictionary=True)
        cur.execute(
            """
            SELECT tender_id, source_portal
            FROM   tender_hashes
            WHERE  content_hash = %s
              AND  tender_id    != %s
            LIMIT  1
            """,
            (content_hash, tender_id),
        )
        row = cur.fetchone()
        cur.close()
        conn.close()

        if row:
            return DedupResult(
                is_new        = False,
                canonical_id  = row["tender_id"],
                dedup_type    = "hash",
                source_portal = row.get("source_portal"),
            )
        return None

    except Exception as exc:
        logger.warning(f"[dedup] hash check failed (non-fatal): {exc}")
        return None   # fail-open: assume new if DB unavailable


def _store_hash_fingerprint(
    content_hash:  str,
    tender_id:     str,
    source_portal: str = "",
) -> bool:
    """Insert into tender_hashes. INSERT IGNORE = idempotent."""
    if not content_hash:
        return False
    try:
        from database.db import get_connection
        conn = get_connection()
        cur  = conn.cursor()
        cur.execute(
            """
            INSERT IGNORE INTO tender_hashes
                (content_hash, tender_id, source_portal)
            VALUES (%s, %s, %s)
            """,
            (content_hash, tender_id, source_portal[:100] if source_portal else ""),
        )
        conn.commit()
        cur.close()
        conn.close()
        return True
    except Exception as exc:
        logger.warning(f"[dedup] store hash failed (non-fatal): {exc}")
        return False


# =============================================================================
# Level 2 — Semantic dedup helpers
# =============================================================================

def _check_semantic_duplicate(
    embedding:   object,
    tender_id:   str,
    title:       str,
    threshold:   float,
) -> Optional[DedupResult]:
    """
    Query ChromaDB for a near-duplicate.
    Returns DedupResult(is_new=False) if similarity ≥ threshold, else None.
    """
    try:
        from intelligence.vector_store import is_duplicate
        if is_duplicate(embedding, threshold=threshold):
            return DedupResult(
                is_new     = False,
                dedup_type = "semantic",
                similarity = threshold,   # at least this similar
            )
        return None
    except Exception as exc:
        logger.debug(f"[dedup] semantic check skipped: {exc}")
        return None   # fail-open


# =============================================================================
# DB schema helper — called from db.init_db()
# =============================================================================

def init_hash_schema() -> None:
    """
    Create the tender_hashes table used for Level 1 fingerprint dedup.
    Safe to call repeatedly (uses CREATE TABLE IF NOT EXISTS).
    Called automatically by db.init_db().
    """
    try:
        from database.db import get_connection
        conn = get_connection()
        cur  = conn.cursor()
        cur.execute("""
            CREATE TABLE IF NOT EXISTS tender_hashes (
                id            INT AUTO_INCREMENT PRIMARY KEY,
                content_hash  VARCHAR(32)   NOT NULL,
                tender_id     VARCHAR(255)  NOT NULL,
                source_portal VARCHAR(100)  DEFAULT '',
                created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                UNIQUE KEY uq_hash_portal (content_hash, source_portal),
                INDEX idx_tender_id (tender_id)
            ) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
        """)
        conn.commit()
        cur.close()
        conn.close()
        logger.info("[dedup] tender_hashes table ready")
    except Exception as exc:
        logger.warning(f"[dedup] init_hash_schema failed (non-fatal): {exc}")
